apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-test
  template:
    metadata:
      labels:
        app: frontend-test
    spec:
      containers:
        - name: frontend-test
          image: us-central1-docker.pkg.dev/tejal-project/tejal-projects/frontend-test:latest
          ports:
            - containerPort: 3000
